MVC4FormsAuth.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC4FormsAuth.Web.Controllers
{
    public class HomeController : Controller
    {
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC4FormsAuth.Web/Controllers/LoginController.cs
using MVC4FormsAuth.Managers;
using MVC4FormsAuth.Types.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC4FormsAuth.Web.Controllers
{
    public class LoginController : Controller
    {
        [HttpPost]
        [AllowAnonymous]
        public JsonResult Login(Logon logon)
        {
            string status = "The username or password provided is incorrect.";

            // Verify the fields.
            if (ModelState.IsValid)
            {
                // Authenticate the user.
                if (UserManager.ValidateUser(logon, Response))
                {
                    // Redirect to the secure area.
                    if (string.IsNullOrWhiteSpace(logon.RedirectUrl))
                    {
                        logon.RedirectUrl = "/";
                    }

                    status = "OK";
                }
            }

            return Json(new { RedirectUrl = logon.RedirectUrl, Status = status });
        }

        public ActionResult Logout()
        {
            // Clear the user session and forms auth ticket.
            UserManager.Logoff(Session, Response);

            return RedirectToAction("Index", "Home");
        }
    }
}

MVC4FormsAuth.Web/Views/Home/Index.cshtml
@using MVC4FormsAuth.Managers
@using MVC4FormsAuth.Types.Models

@{
    Layout = "~/views/shared/layouts/default.cshtml";
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (User.Identity.IsAuthenticated)
{
    <div>
        You're logged in as @UserManager.User.Username (@UserManager.User.Age)
    </div>
}
else
{
    @Html.Partial("Controls/Login", new Logon());
}

MVC4FormsAuth.Web/Views/Shared/Controls/Login.cshtml
@using MVC4FormsAuth.Types.Models

@model Logon

@{ Html.EnableClientValidation(); }

<script type="text/javascript">
    $(document).ready(function () {
        // Set form to submit as ajax.
        $('#loginForm').ajaxForm({
            dataType: 'json',
            beforeSubmit: function (arr, $form, options) {
                if (!$form.valid()) {
                    return false;
                }
            },
            success: function (result) {
                // Send user to landing page.
                if (result.Status == 'OK') {
                    document.location = result.RedirectUrl;
                }
                else {
                    $('#loginStatus').html(result.Status);
                }
            }
        });
    });
</script>

@using (Html.BeginForm("Index", "Login", FormMethod.Post, new { id = "loginForm" }))
{                              
    @Html.HiddenFor(u => u.RedirectUrl, new { value = Model.RedirectUrl })

    <div id="loginStatus" class="field-validation-error"></div>
    
    <div>@Html.LabelFor(u => u.Username)</div>
    <div>@Html.TextBoxFor(u => u.Username, new { id = "userid", @class = "inptFld" })</div>
    
    <div>@Html.LabelFor(u => u.Password)</div>
    <div>@Html.PasswordFor(u => u.Password, new { id = "passowdid", @class = "inptFld" })</div>
    
    <input type="submit" value="Login" />
}

MVC4FormsAuth.Web/Views/Shared/Layouts/default.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>MVC4FormsAuth | @ViewBag.Title</title>
    <meta name="description" content="@ViewBag.Description" />
    <meta name="keywords" content="@ViewBag.Keywords" />
    <link rel="Stylesheet" href="@Href("~/styles/style.css")" type="text/css" />
    <script src="http://code.jquery.com/jquery-1.8.3.min.js" type="text/javascript"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js" type="text/javascript"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
    <script src="http://malsup.github.com/jquery.form.js" type="text/javascript"></script>    
</head>
<body>
    @RenderBody()
</body>
</html>